apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
   name: emqx
spec:
   image: emqx:5
   coreTemplate:
      spec:
         resources:
            requests:
              memory: "64Mi"
              cpu: "125m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
         volumeClaimTemplates:
            storageClassName: longhorn
            resources:
               requests:
                  storage: 20Mi
            accessModes:
               - ReadWriteOnce
         replicas: 3
   listenersServiceTemplate:
      spec:
         type: LoadBalancer
         loadBalancerIP: 192.168.254.15
   dashboardServiceTemplate:
      spec:
         type: LoadBalancer
         loadBalancerIP: 192.168.254.16
   updateStrategy:
      evacuationStrategy:
         connEvictRate: 1000
         sessEvictRate: 1000
         waitTakeover: 10
      initialDelaySeconds: 10
      type: Recreate
