apiVersion: apps.emqx.io/v2beta1
kind: EMQX
metadata:
   name: emqx
spec:
   image: emqx:5
   serviceTemplate:
     spec:
       type: LoadBalancer
       loadBalancerIP: 192.168.254.15
   dashboardServiceTemplate:
      spec:
        type: LoadBalancer
        loadBalancerIP: 192.168.254.16
